In [2]:
import numpy as np
import pandas as pd
import category_encoders as ce
import matplotlib.pyplot as plt 
import seaborn as sb

In [3]:
 # -- 1. #3  (age)       
 #      -- 2. #4  (sex)       
 #      -- 3. #9  (cp)        
 #      -- 4. #10 (trestbps)  
 #      -- 5. #12 (chol)      
 #      -- 6. #16 (fbs)       
 #      -- 7. #19 (restecg)   
 #      -- 8. #32 (thalach)  
 #      -- 10. #40 (oldpeak)    
 #      -- 9. #38 (exang)     
 #      -- 11. #41 (slope)     
 #      -- 12. #44 (ca)        
 #      -- 13. #51 (thal)      
 #      -- 14. #58 (num) 
cols = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']

In [6]:
file_path = r"C:\Users\balaj\OneDrive\Desktop\disease prediction models\raw_data\processed.cleveland.data".replace("\\", "/")
print(f"Modified File Path: {file_path}")

Modified File Path: C:/Users/balaj/OneDrive/Desktop/disease prediction models/raw_data/processed.cleveland.data

In [7]:
with open(file_path, 'r') as f:
    text = f.read()

In [8]:
for line in text.splitlines():
    print(line)

63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3
57.0,0.0,4.0,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0
63.0,1.0,4.0,130.0,254.0,0.0,2.0,147.0,0.0,1.4,2.0,1.0,7.0,2
53.0,1.0,4.0,140.0,203.0,1.0,2.0,155.0,1.0,3.1,3.0,0.0,7.0,1
57.0,1.0,4.0,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,0
56.0,0.0,2.0,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,0
56.0,1.0,3.0,130.0,256.0,1.0,2.0,142.0,1.0,0.6,2.0,1.0,6.0,2
44.0,1.0,2.0,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,0
52.0,1.0,3.0,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,0
57.0,1.0,3.0,150.0,168.0,0.0,0.0,174.0,0.0,1.6,1.0,0.0,3.0,0
48.0,1.0,2.0,110.0,229.0,0.0,0.0,168.0,0.0,1.0,3.0,0.0,7.0,1
54.0,1.0,4.0,140.0,239.0,0.0,0.0,160.0,0.0,1.2,1.0,0.0,3.0,0
48.0,0.0,3.0,130.0,275.0,0.0,0.0,139.0,0.0,0.2,1.0,0.0,3.0,0
49.0,1.0,2.0,130.0,266.0,0.0,0.0,171.0,0.0,0.6,1.0,0.0,3.0,0
64.0,1.0,1.0,110.0,211.0,0.0,2.0,144.0,1.0,1.8,2.0,0.0,3.0,0
58.0,0.0,1.0,150.0,283.0,1.0,2.0,162.0,0.0,1.0,1.0,0.0,3.0,0
58.0,1.0,2.0,120.0,284.0,0.0,2.0,160.0,0.0,1.8,2.0,0.0,3.0,1
58.0,1.0,3.0,132.0,224.0,0.0,2.0,173.0,0.0,3.2,1.0,2.0,7.0,3
60.0,1.0,4.0,130.0,206.0,0.0,2.0,132.0,1.0,2.4,2.0,2.0,7.0,4
50.0,0.0,3.0,120.0,219.0,0.0,0.0,158.0,0.0,1.6,2.0,0.0,3.0,0
58.0,0.0,3.0,120.0,340.0,0.0,0.0,172.0,0.0,0.0,1.0,0.0,3.0,0
66.0,0.0,1.0,150.0,226.0,0.0,0.0,114.0,0.0,2.6,3.0,0.0,3.0,0
43.0,1.0,4.0,150.0,247.0,0.0,0.0,171.0,0.0,1.5,1.0,0.0,3.0,0
40.0,1.0,4.0,110.0,167.0,0.0,2.0,114.0,1.0,2.0,2.0,0.0,7.0,3
69.0,0.0,1.0,140.0,239.0,0.0,0.0,151.0,0.0,1.8,1.0,2.0,3.0,0
60.0,1.0,4.0,117.0,230.0,1.0,0.0,160.0,1.0,1.4,1.0,2.0,7.0,2
64.0,1.0,3.0,140.0,335.0,0.0,0.0,158.0,0.0,0.0,1.0,0.0,3.0,1
59.0,1.0,4.0,135.0,234.0,0.0,0.0,161.0,0.0,0.5,2.0,0.0,7.0,0
44.0,1.0,3.0,130.0,233.0,0.0,0.0,179.0,1.0,0.4,1.0,0.0,3.0,0
42.0,1.0,4.0,140.0,226.0,0.0,0.0,178.0,0.0,0.0,1.0,0.0,3.0,0
43.0,1.0,4.0,120.0,177.0,0.0,2.0,120.0,1.0,2.5,2.0,0.0,7.0,3
57.0,1.0,4.0,150.0,276.0,0.0,2.0,112.0,1.0,0.6,2.0,1.0,6.0,1
55.0,1.0,4.0,132.0,353.0,0.0,0.0,132.0,1.0,1.2,2.0,1.0,7.0,3
61.0,1.0,3.0,150.0,243.0,1.0,0.0,137.0,1.0,1.0,2.0,0.0,3.0,0
65.0,0.0,4.0,150.0,225.0,0.0,2.0,114.0,0.0,1.0,2.0,3.0,7.0,4
40.0,1.0,1.0,140.0,199.0,0.0,0.0,178.0,1.0,1.4,1.0,0.0,7.0,0
71.0,0.0,2.0,160.0,302.0,0.0,0.0,162.0,0.0,0.4,1.0,2.0,3.0,0
59.0,1.0,3.0,150.0,212.0,1.0,0.0,157.0,0.0,1.6,1.0,0.0,3.0,0
61.0,0.0,4.0,130.0,330.0,0.0,2.0,169.0,0.0,0.0,1.0,0.0,3.0,1
58.0,1.0,3.0,112.0,230.0,0.0,2.0,165.0,0.0,2.5,2.0,1.0,7.0,4
51.0,1.0,3.0,110.0,175.0,0.0,0.0,123.0,0.0,0.6,1.0,0.0,3.0,0
50.0,1.0,4.0,150.0,243.0,0.0,2.0,128.0,0.0,2.6,2.0,0.0,7.0,4
65.0,0.0,3.0,140.0,417.0,1.0,2.0,157.0,0.0,0.8,1.0,1.0,3.0,0
53.0,1.0,3.0,130.0,197.0,1.0,2.0,152.0,0.0,1.2,3.0,0.0,3.0,0
41.0,0.0,2.0,105.0,198.0,0.0,0.0,168.0,0.0,0.0,1.0,1.0,3.0,0
65.0,1.0,4.0,120.0,177.0,0.0,0.0,140.0,0.0,0.4,1.0,0.0,7.0,0
44.0,1.0,4.0,112.0,290.0,0.0,2.0,153.0,0.0,0.0,1.0,1.0,3.0,2
44.0,1.0,2.0,130.0,219.0,0.0,2.0,188.0,0.0,0.0,1.0,0.0,3.0,0
60.0,1.0,4.0,130.0,253.0,0.0,0.0,144.0,1.0,1.4,1.0,1.0,7.0,1
54.0,1.0,4.0,124.0,266.0,0.0,2.0,109.0,1.0,2.2,2.0,1.0,7.0,1
50.0,1.0,3.0,140.0,233.0,0.0,0.0,163.0,0.0,0.6,2.0,1.0,7.0,1
41.0,1.0,4.0,110.0,172.0,0.0,2.0,158.0,0.0,0.0,1.0,0.0,7.0,1
54.0,1.0,3.0,125.0,273.0,0.0,2.0,152.0,0.0,0.5,3.0,1.0,3.0,0
51.0,1.0,1.0,125.0,213.0,0.0,2.0,125.0,1.0,1.4,1.0,1.0,3.0,0
51.0,0.0,4.0,130.0,305.0,0.0,0.0,142.0,1.0,1.2,2.0,0.0,7.0,2
46.0,0.0,3.0,142.0,177.0,0.0,2.0,160.0,1.0,1.4,3.0,0.0,3.0,0
58.0,1.0,4.0,128.0,216.0,0.0,2.0,131.0,1.0,2.2,2.0,3.0,7.0,1
54.0,0.0,3.0,135.0,304.0,1.0,0.0,170.0,0.0,0.0,1.0,0.0,3.0,0
54.0,1.0,4.0,120.0,188.0,0.0,0.0,113.0,0.0,1.4,2.0,1.0,7.0,2
60.0,1.0,4.0,145.0,282.0,0.0,2.0,142.0,1.0,2.8,2.0,2.0,7.0,2
60.0,1.0,3.0,140.0,185.0,0.0,2.0,155.0,0.0,3.0,2.0,0.0,3.0,1
54.0,1.0,3.0,150.0,232.0,0.0,2.0,165.0,0.0,1.6,1.0,0.0,7.0,0
59.0,1.0,4.0,170.0,326.0,0.0,2.0,140.0,1.0,3.4,3.0,0.0,7.0,2
46.0,1.0,3.0,150.0,231.0,0.0,0.0,147.0,0.0,3.6,2.0,0.0,3.0,1
65.0,0.0,3.0,155.0,269.0,0.0,0.0,148.0,0.0,0.8,1.0,0.0,3.0,0
67.0,1.0,4.0,125.0,254.0,1.0,0.0,163.0,0.0,0.2,2.0,2.0,7.0,3
62.0,1.0,4.0,120.0,267.0,0.0,0.0,99.0,1.0,1.8,2.0,2.0,7.0,1
65.0,1.0,4.0,110.0,248.0,0.0,2.0,158.0,0.0,0.6,1.0,2.0,6.0,1
44.0,1.0,4.0,110.0,197.0,0.0,2.0,177.0,0.0,0.0,1.0,1.0,3.0,1
65.0,0.0,3.0,160.0,360.0,0.0,2.0,151.0,0.0,0.8,1.0,0.0,3.0,0
60.0,1.0,4.0,125.0,258.0,0.0,2.0,141.0,1.0,2.8,2.0,1.0,7.0,1
51.0,0.0,3.0,140.0,308.0,0.0,2.0,142.0,0.0,1.5,1.0,1.0,3.0,0
48.0,1.0,2.0,130.0,245.0,0.0,2.0,180.0,0.0,0.2,2.0,0.0,3.0,0
58.0,1.0,4.0,150.0,270.0,0.0,2.0,111.0,1.0,0.8,1.0,0.0,7.0,3
45.0,1.0,4.0,104.0,208.0,0.0,2.0,148.0,1.0,3.0,2.0,0.0,3.0,0
53.0,0.0,4.0,130.0,264.0,0.0,2.0,143.0,0.0,0.4,2.0,0.0,3.0,0
39.0,1.0,3.0,140.0,321.0,0.0,2.0,182.0,0.0,0.0,1.0,0.0,3.0,0
68.0,1.0,3.0,180.0,274.0,1.0,2.0,150.0,1.0,1.6,2.0,0.0,7.0,3
52.0,1.0,2.0,120.0,325.0,0.0,0.0,172.0,0.0,0.2,1.0,0.0,3.0,0
44.0,1.0,3.0,140.0,235.0,0.0,2.0,180.0,0.0,0.0,1.0,0.0,3.0,0
47.0,1.0,3.0,138.0,257.0,0.0,2.0,156.0,0.0,0.0,1.0,0.0,3.0,0
53.0,0.0,3.0,128.0,216.0,0.0,2.0,115.0,0.0,0.0,1.0,0.0,?,0
53.0,0.0,4.0,138.0,234.0,0.0,2.0,160.0,0.0,0.0,1.0,0.0,3.0,0
51.0,0.0,3.0,130.0,256.0,0.0,2.0,149.0,0.0,0.5,1.0,0.0,3.0,0
66.0,1.0,4.0,120.0,302.0,0.0,2.0,151.0,0.0,0.4,2.0,0.0,3.0,0
62.0,0.0,4.0,160.0,164.0,0.0,2.0,145.0,0.0,6.2,3.0,3.0,7.0,3
62.0,1.0,3.0,130.0,231.0,0.0,0.0,146.0,0.0,1.8,2.0,3.0,7.0,0
44.0,0.0,3.0,108.0,141.0,0.0,0.0,175.0,0.0,0.6,2.0,0.0,3.0,0
63.0,0.0,3.0,135.0,252.0,0.0,2.0,172.0,0.0,0.0,1.0,0.0,3.0,0
52.0,1.0,4.0,128.0,255.0,0.0,0.0,161.0,1.0,0.0,1.0,1.0,7.0,1
59.0,1.0,4.0,110.0,239.0,0.0,2.0,142.0,1.0,1.2,2.0,1.0,7.0,2
60.0,0.0,4.0,150.0,258.0,0.0,2.0,157.0,0.0,2.6,2.0,2.0,7.0,3
52.0,1.0,2.0,134.0,201.0,0.0,0.0,158.0,0.0,0.8,1.0,1.0,3.0,0
48.0,1.0,4.0,122.0,222.0,0.0,2.0,186.0,0.0,0.0,1.0,0.0,3.0,0
45.0,1.0,4.0,115.0,260.0,0.0,2.0,185.0,0.0,0.0,1.0,0.0,3.0,0
34.0,1.0,1.0,118.0,182.0,0.0,2.0,174.0,0.0,0.0,1.0,0.0,3.0,0
57.0,0.0,4.0,128.0,303.0,0.0,2.0,159.0,0.0,0.0,1.0,1.0,3.0,0
71.0,0.0,3.0,110.0,265.0,1.0,2.0,130.0,0.0,0.0,1.0,1.0,3.0,0
49.0,1.0,3.0,120.0,188.0,0.0,0.0,139.0,0.0,2.0,2.0,3.0,7.0,3
54.0,1.0,2.0,108.0,309.0,0.0,0.0,156.0,0.0,0.0,1.0,0.0,7.0,0
59.0,1.0,4.0,140.0,177.0,0.0,0.0,162.0,1.0,0.0,1.0,1.0,7.0,2
57.0,1.0,3.0,128.0,229.0,0.0,2.0,150.0,0.0,0.4,2.0,1.0,7.0,1
61.0,1.0,4.0,120.0,260.0,0.0,0.0,140.0,1.0,3.6,2.0,1.0,7.0,2
39.0,1.0,4.0,118.0,219.0,0.0,0.0,140.0,0.0,1.2,2.0,0.0,7.0,3
61.0,0.0,4.0,145.0,307.0,0.0,2.0,146.0,1.0,1.0,2.0,0.0,7.0,1
56.0,1.0,4.0,125.0,249.0,1.0,2.0,144.0,1.0,1.2,2.0,1.0,3.0,1
52.0,1.0,1.0,118.0,186.0,0.0,2.0,190.0,0.0,0.0,2.0,0.0,6.0,0
43.0,0.0,4.0,132.0,341.0,1.0,2.0,136.0,1.0,3.0,2.0,0.0,7.0,2
62.0,0.0,3.0,130.0,263.0,0.0,0.0,97.0,0.0,1.2,2.0,1.0,7.0,2
41.0,1.0,2.0,135.0,203.0,0.0,0.0,132.0,0.0,0.0,2.0,0.0,6.0,0
58.0,1.0,3.0,140.0,211.0,1.0,2.0,165.0,0.0,0.0,1.0,0.0,3.0,0
35.0,0.0,4.0,138.0,183.0,0.0,0.0,182.0,0.0,1.4,1.0,0.0,3.0,0
63.0,1.0,4.0,130.0,330.0,1.0,2.0,132.0,1.0,1.8,1.0,3.0,7.0,3
65.0,1.0,4.0,135.0,254.0,0.0,2.0,127.0,0.0,2.8,2.0,1.0,7.0,2
48.0,1.0,4.0,130.0,256.0,1.0,2.0,150.0,1.0,0.0,1.0,2.0,7.0,3
63.0,0.0,4.0,150.0,407.0,0.0,2.0,154.0,0.0,4.0,2.0,3.0,7.0,4
51.0,1.0,3.0,100.0,222.0,0.0,0.0,143.0,1.0,1.2,2.0,0.0,3.0,0
55.0,1.0,4.0,140.0,217.0,0.0,0.0,111.0,1.0,5.6,3.0,0.0,7.0,3
65.0,1.0,1.0,138.0,282.0,1.0,2.0,174.0,0.0,1.4,2.0,1.0,3.0,1
45.0,0.0,2.0,130.0,234.0,0.0,2.0,175.0,0.0,0.6,2.0,0.0,3.0,0
56.0,0.0,4.0,200.0,288.0,1.0,2.0,133.0,1.0,4.0,3.0,2.0,7.0,3
54.0,1.0,4.0,110.0,239.0,0.0,0.0,126.0,1.0,2.8,2.0,1.0,7.0,3
44.0,1.0,2.0,120.0,220.0,0.0,0.0,170.0,0.0,0.0,1.0,0.0,3.0,0
62.0,0.0,4.0,124.0,209.0,0.0,0.0,163.0,0.0,0.0,1.0,0.0,3.0,0
54.0,1.0,3.0,120.0,258.0,0.0,2.0,147.0,0.0,0.4,2.0,0.0,7.0,0
51.0,1.0,3.0,94.0,227.0,0.0,0.0,154.0,1.0,0.0,1.0,1.0,7.0,0
29.0,1.0,2.0,130.0,204.0,0.0,2.0,202.0,0.0,0.0,1.0,0.0,3.0,0
51.0,1.0,4.0,140.0,261.0,0.0,2.0,186.0,1.0,0.0,1.0,0.0,3.0,0
43.0,0.0,3.0,122.0,213.0,0.0,0.0,165.0,0.0,0.2,2.0,0.0,3.0,0
55.0,0.0,2.0,135.0,250.0,0.0,2.0,161.0,0.0,1.4,2.0,0.0,3.0,0
70.0,1.0,4.0,145.0,174.0,0.0,0.0,125.0,1.0,2.6,3.0,0.0,7.0,4
62.0,1.0,2.0,120.0,281.0,0.0,2.0,103.0,0.0,1.4,2.0,1.0,7.0,3
35.0,1.0,4.0,120.0,198.0,0.0,0.0,130.0,1.0,1.6,2.0,0.0,7.0,1
51.0,1.0,3.0,125.0,245.0,1.0,2.0,166.0,0.0,2.4,2.0,0.0,3.0,0
59.0,1.0,2.0,140.0,221.0,0.0,0.0,164.0,1.0,0.0,1.0,0.0,3.0,0
59.0,1.0,1.0,170.0,288.0,0.0,2.0,159.0,0.0,0.2,2.0,0.0,7.0,1
52.0,1.0,2.0,128.0,205.0,1.0,0.0,184.0,0.0,0.0,1.0,0.0,3.0,0
64.0,1.0,3.0,125.0,309.0,0.0,0.0,131.0,1.0,1.8,2.0,0.0,7.0,1
58.0,1.0,3.0,105.0,240.0,0.0,2.0,154.0,1.0,0.6,2.0,0.0,7.0,0
47.0,1.0,3.0,108.0,243.0,0.0,0.0,152.0,0.0,0.0,1.0,0.0,3.0,1
57.0,1.0,4.0,165.0,289.0,1.0,2.0,124.0,0.0,1.0,2.0,3.0,7.0,4
41.0,1.0,3.0,112.0,250.0,0.0,0.0,179.0,0.0,0.0,1.0,0.0,3.0,0
45.0,1.0,2.0,128.0,308.0,0.0,2.0,170.0,0.0,0.0,1.0,0.0,3.0,0
60.0,0.0,3.0,102.0,318.0,0.0,0.0,160.0,0.0,0.0,1.0,1.0,3.0,0
52.0,1.0,1.0,152.0,298.0,1.0,0.0,178.0,0.0,1.2,2.0,0.0,7.0,0
42.0,0.0,4.0,102.0,265.0,0.0,2.0,122.0,0.0,0.6,2.0,0.0,3.0,0
67.0,0.0,3.0,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,0
55.0,1.0,4.0,160.0,289.0,0.0,2.0,145.0,1.0,0.8,2.0,1.0,7.0,4
64.0,1.0,4.0,120.0,246.0,0.0,2.0,96.0,1.0,2.2,3.0,1.0,3.0,3
70.0,1.0,4.0,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,1
51.0,1.0,4.0,140.0,299.0,0.0,0.0,173.0,1.0,1.6,1.0,0.0,7.0,1
58.0,1.0,4.0,125.0,300.0,0.0,2.0,171.0,0.0,0.0,1.0,2.0,7.0,1
60.0,1.0,4.0,140.0,293.0,0.0,2.0,170.0,0.0,1.2,2.0,2.0,7.0,2
68.0,1.0,3.0,118.0,277.0,0.0,0.0,151.0,0.0,1.0,1.0,1.0,7.0,0
46.0,1.0,2.0,101.0,197.0,1.0,0.0,156.0,0.0,0.0,1.0,0.0,7.0,0
77.0,1.0,4.0,125.0,304.0,0.0,2.0,162.0,1.0,0.0,1.0,3.0,3.0,4
54.0,0.0,3.0,110.0,214.0,0.0,0.0,158.0,0.0,1.6,2.0,0.0,3.0,0
58.0,0.0,4.0,100.0,248.0,0.0,2.0,122.0,0.0,1.0,2.0,0.0,3.0,0
48.0,1.0,3.0,124.0,255.0,1.0,0.0,175.0,0.0,0.0,1.0,2.0,3.0,0
57.0,1.0,4.0,132.0,207.0,0.0,0.0,168.0,1.0,0.0,1.0,0.0,7.0,0
52.0,1.0,3.0,138.0,223.0,0.0,0.0,169.0,0.0,0.0,1.0,?,3.0,0
54.0,0.0,2.0,132.0,288.0,1.0,2.0,159.0,1.0,0.0,1.0,1.0,3.0,0
35.0,1.0,4.0,126.0,282.0,0.0,2.0,156.0,1.0,0.0,1.0,0.0,7.0,1
45.0,0.0,2.0,112.0,160.0,0.0,0.0,138.0,0.0,0.0,2.0,0.0,3.0,0
70.0,1.0,3.0,160.0,269.0,0.0,0.0,112.0,1.0,2.9,2.0,1.0,7.0,3
53.0,1.0,4.0,142.0,226.0,0.0,2.0,111.0,1.0,0.0,1.0,0.0,7.0,0
59.0,0.0,4.0,174.0,249.0,0.0,0.0,143.0,1.0,0.0,2.0,0.0,3.0,1
62.0,0.0,4.0,140.0,394.0,0.0,2.0,157.0,0.0,1.2,2.0,0.0,3.0,0
64.0,1.0,4.0,145.0,212.0,0.0,2.0,132.0,0.0,2.0,2.0,2.0,6.0,4
57.0,1.0,4.0,152.0,274.0,0.0,0.0,88.0,1.0,1.2,2.0,1.0,7.0,1
52.0,1.0,4.0,108.0,233.0,1.0,0.0,147.0,0.0,0.1,1.0,3.0,7.0,0
56.0,1.0,4.0,132.0,184.0,0.0,2.0,105.0,1.0,2.1,2.0,1.0,6.0,1
43.0,1.0,3.0,130.0,315.0,0.0,0.0,162.0,0.0,1.9,1.0,1.0,3.0,0
53.0,1.0,3.0,130.0,246.0,1.0,2.0,173.0,0.0,0.0,1.0,3.0,3.0,0
48.0,1.0,4.0,124.0,274.0,0.0,2.0,166.0,0.0,0.5,2.0,0.0,7.0,3
56.0,0.0,4.0,134.0,409.0,0.0,2.0,150.0,1.0,1.9,2.0,2.0,7.0,2
42.0,1.0,1.0,148.0,244.0,0.0,2.0,178.0,0.0,0.8,1.0,2.0,3.0,0
59.0,1.0,1.0,178.0,270.0,0.0,2.0,145.0,0.0,4.2,3.0,0.0,7.0,0
60.0,0.0,4.0,158.0,305.0,0.0,2.0,161.0,0.0,0.0,1.0,0.0,3.0,1
63.0,0.0,2.0,140.0,195.0,0.0,0.0,179.0,0.0,0.0,1.0,2.0,3.0,0
42.0,1.0,3.0,120.0,240.0,1.0,0.0,194.0,0.0,0.8,3.0,0.0,7.0,0
66.0,1.0,2.0,160.0,246.0,0.0,0.0,120.0,1.0,0.0,2.0,3.0,6.0,2
54.0,1.0,2.0,192.0,283.0,0.0,2.0,195.0,0.0,0.0,1.0,1.0,7.0,1
69.0,1.0,3.0,140.0,254.0,0.0,2.0,146.0,0.0,2.0,2.0,3.0,7.0,2
50.0,1.0,3.0,129.0,196.0,0.0,0.0,163.0,0.0,0.0,1.0,0.0,3.0,0
51.0,1.0,4.0,140.0,298.0,0.0,0.0,122.0,1.0,4.2,2.0,3.0,7.0,3
43.0,1.0,4.0,132.0,247.0,1.0,2.0,143.0,1.0,0.1,2.0,?,7.0,1
62.0,0.0,4.0,138.0,294.0,1.0,0.0,106.0,0.0,1.9,2.0,3.0,3.0,2
68.0,0.0,3.0,120.0,211.0,0.0,2.0,115.0,0.0,1.5,2.0,0.0,3.0,0
67.0,1.0,4.0,100.0,299.0,0.0,2.0,125.0,1.0,0.9,2.0,2.0,3.0,3
69.0,1.0,1.0,160.0,234.0,1.0,2.0,131.0,0.0,0.1,2.0,1.0,3.0,0
45.0,0.0,4.0,138.0,236.0,0.0,2.0,152.0,1.0,0.2,2.0,0.0,3.0,0
50.0,0.0,2.0,120.0,244.0,0.0,0.0,162.0,0.0,1.1,1.0,0.0,3.0,0
59.0,1.0,1.0,160.0,273.0,0.0,2.0,125.0,0.0,0.0,1.0,0.0,3.0,1
50.0,0.0,4.0,110.0,254.0,0.0,2.0,159.0,0.0,0.0,1.0,0.0,3.0,0
64.0,0.0,4.0,180.0,325.0,0.0,0.0,154.0,1.0,0.0,1.0,0.0,3.0,0
57.0,1.0,3.0,150.0,126.0,1.0,0.0,173.0,0.0,0.2,1.0,1.0,7.0,0
64.0,0.0,3.0,140.0,313.0,0.0,0.0,133.0,0.0,0.2,1.0,0.0,7.0,0
43.0,1.0,4.0,110.0,211.0,0.0,0.0,161.0,0.0,0.0,1.0,0.0,7.0,0
45.0,1.0,4.0,142.0,309.0,0.0,2.0,147.0,1.0,0.0,2.0,3.0,7.0,3
58.0,1.0,4.0,128.0,259.0,0.0,2.0,130.0,1.0,3.0,2.0,2.0,7.0,3
50.0,1.0,4.0,144.0,200.0,0.0,2.0,126.0,1.0,0.9,2.0,0.0,7.0,3
55.0,1.0,2.0,130.0,262.0,0.0,0.0,155.0,0.0,0.0,1.0,0.0,3.0,0
62.0,0.0,4.0,150.0,244.0,0.0,0.0,154.0,1.0,1.4,2.0,0.0,3.0,1
37.0,0.0,3.0,120.0,215.0,0.0,0.0,170.0,0.0,0.0,1.0,0.0,3.0,0
38.0,1.0,1.0,120.0,231.0,0.0,0.0,182.0,1.0,3.8,2.0,0.0,7.0,4
41.0,1.0,3.0,130.0,214.0,0.0,2.0,168.0,0.0,2.0,2.0,0.0,3.0,0
66.0,0.0,4.0,178.0,228.0,1.0,0.0,165.0,1.0,1.0,2.0,2.0,7.0,3
52.0,1.0,4.0,112.0,230.0,0.0,0.0,160.0,0.0,0.0,1.0,1.0,3.0,1
56.0,1.0,1.0,120.0,193.0,0.0,2.0,162.0,0.0,1.9,2.0,0.0,7.0,0
46.0,0.0,2.0,105.0,204.0,0.0,0.0,172.0,0.0,0.0,1.0,0.0,3.0,0
46.0,0.0,4.0,138.0,243.0,0.0,2.0,152.0,1.0,0.0,2.0,0.0,3.0,0
64.0,0.0,4.0,130.0,303.0,0.0,0.0,122.0,0.0,2.0,2.0,2.0,3.0,0
59.0,1.0,4.0,138.0,271.0,0.0,2.0,182.0,0.0,0.0,1.0,0.0,3.0,0
41.0,0.0,3.0,112.0,268.0,0.0,2.0,172.0,1.0,0.0,1.0,0.0,3.0,0
54.0,0.0,3.0,108.0,267.0,0.0,2.0,167.0,0.0,0.0,1.0,0.0,3.0,0
39.0,0.0,3.0,94.0,199.0,0.0,0.0,179.0,0.0,0.0,1.0,0.0,3.0,0
53.0,1.0,4.0,123.0,282.0,0.0,0.0,95.0,1.0,2.0,2.0,2.0,7.0,3
63.0,0.0,4.0,108.0,269.0,0.0,0.0,169.0,1.0,1.8,2.0,2.0,3.0,1
34.0,0.0,2.0,118.0,210.0,0.0,0.0,192.0,0.0,0.7,1.0,0.0,3.0,0
47.0,1.0,4.0,112.0,204.0,0.0,0.0,143.0,0.0,0.1,1.0,0.0,3.0,0
67.0,0.0,3.0,152.0,277.0,0.0,0.0,172.0,0.0,0.0,1.0,1.0,3.0,0
54.0,1.0,4.0,110.0,206.0,0.0,2.0,108.0,1.0,0.0,2.0,1.0,3.0,3
66.0,1.0,4.0,112.0,212.0,0.0,2.0,132.0,1.0,0.1,1.0,1.0,3.0,2
52.0,0.0,3.0,136.0,196.0,0.0,2.0,169.0,0.0,0.1,2.0,0.0,3.0,0
55.0,0.0,4.0,180.0,327.0,0.0,1.0,117.0,1.0,3.4,2.0,0.0,3.0,2
49.0,1.0,3.0,118.0,149.0,0.0,2.0,126.0,0.0,0.8,1.0,3.0,3.0,1
74.0,0.0,2.0,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,0
54.0,0.0,3.0,160.0,201.0,0.0,0.0,163.0,0.0,0.0,1.0,1.0,3.0,0
54.0,1.0,4.0,122.0,286.0,0.0,2.0,116.0,1.0,3.2,2.0,2.0,3.0,3
56.0,1.0,4.0,130.0,283.0,1.0,2.0,103.0,1.0,1.6,3.0,0.0,7.0,2
46.0,1.0,4.0,120.0,249.0,0.0,2.0,144.0,0.0,0.8,1.0,0.0,7.0,1
49.0,0.0,2.0,134.0,271.0,0.0,0.0,162.0,0.0,0.0,2.0,0.0,3.0,0
42.0,1.0,2.0,120.0,295.0,0.0,0.0,162.0,0.0,0.0,1.0,0.0,3.0,0
41.0,1.0,2.0,110.0,235.0,0.0,0.0,153.0,0.0,0.0,1.0,0.0,3.0,0
41.0,0.0,2.0,126.0,306.0,0.0,0.0,163.0,0.0,0.0,1.0,0.0,3.0,0
49.0,0.0,4.0,130.0,269.0,0.0,0.0,163.0,0.0,0.0,1.0,0.0,3.0,0
61.0,1.0,1.0,134.0,234.0,0.0,0.0,145.0,0.0,2.6,2.0,2.0,3.0,2
60.0,0.0,3.0,120.0,178.0,1.0,0.0,96.0,0.0,0.0,1.0,0.0,3.0,0
67.0,1.0,4.0,120.0,237.0,0.0,0.0,71.0,0.0,1.0,2.0,0.0,3.0,2
58.0,1.0,4.0,100.0,234.0,0.0,0.0,156.0,0.0,0.1,1.0,1.0,7.0,2
47.0,1.0,4.0,110.0,275.0,0.0,2.0,118.0,1.0,1.0,2.0,1.0,3.0,1
52.0,1.0,4.0,125.0,212.0,0.0,0.0,168.0,0.0,1.0,1.0,2.0,7.0,3
62.0,1.0,2.0,128.0,208.0,1.0,2.0,140.0,0.0,0.0,1.0,0.0,3.0,0
57.0,1.0,4.0,110.0,201.0,0.0,0.0,126.0,1.0,1.5,2.0,0.0,6.0,0
58.0,1.0,4.0,146.0,218.0,0.0,0.0,105.0,0.0,2.0,2.0,1.0,7.0,1
64.0,1.0,4.0,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,0
51.0,0.0,3.0,120.0,295.0,0.0,2.0,157.0,0.0,0.6,1.0,0.0,3.0,0
43.0,1.0,4.0,115.0,303.0,0.0,0.0,181.0,0.0,1.2,2.0,0.0,3.0,0
42.0,0.0,3.0,120.0,209.0,0.0,0.0,173.0,0.0,0.0,2.0,0.0,3.0,0
67.0,0.0,4.0,106.0,223.0,0.0,0.0,142.0,0.0,0.3,1.0,2.0,3.0,0
76.0,0.0,3.0,140.0,197.0,0.0,1.0,116.0,0.0,1.1,2.0,0.0,3.0,0
70.0,1.0,2.0,156.0,245.0,0.0,2.0,143.0,0.0,0.0,1.0,0.0,3.0,0
57.0,1.0,2.0,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,1
44.0,0.0,3.0,118.0,242.0,0.0,0.0,149.0,0.0,0.3,2.0,1.0,3.0,0
58.0,0.0,2.0,136.0,319.0,1.0,2.0,152.0,0.0,0.0,1.0,2.0,3.0,3
60.0,0.0,1.0,150.0,240.0,0.0,0.0,171.0,0.0,0.9,1.0,0.0,3.0,0
44.0,1.0,3.0,120.0,226.0,0.0,0.0,169.0,0.0,0.0,1.0,0.0,3.0,0
61.0,1.0,4.0,138.0,166.0,0.0,2.0,125.0,1.0,3.6,2.0,1.0,3.0,4
42.0,1.0,4.0,136.0,315.0,0.0,0.0,125.0,1.0,1.8,2.0,0.0,6.0,2
52.0,1.0,4.0,128.0,204.0,1.0,0.0,156.0,1.0,1.0,2.0,0.0,?,2
59.0,1.0,3.0,126.0,218.0,1.0,0.0,134.0,0.0,2.2,2.0,1.0,6.0,2
40.0,1.0,4.0,152.0,223.0,0.0,0.0,181.0,0.0,0.0,1.0,0.0,7.0,1
42.0,1.0,3.0,130.0,180.0,0.0,0.0,150.0,0.0,0.0,1.0,0.0,3.0,0
61.0,1.0,4.0,140.0,207.0,0.0,2.0,138.0,1.0,1.9,1.0,1.0,7.0,1
66.0,1.0,4.0,160.0,228.0,0.0,2.0,138.0,0.0,2.3,1.0,0.0,6.0,0
46.0,1.0,4.0,140.0,311.0,0.0,0.0,120.0,1.0,1.8,2.0,2.0,7.0,2
71.0,0.0,4.0,112.0,149.0,0.0,0.0,125.0,0.0,1.6,2.0,0.0,3.0,0
59.0,1.0,1.0,134.0,204.0,0.0,0.0,162.0,0.0,0.8,1.0,2.0,3.0,1
64.0,1.0,1.0,170.0,227.0,0.0,2.0,155.0,0.0,0.6,2.0,0.0,7.0,0
66.0,0.0,3.0,146.0,278.0,0.0,2.0,152.0,0.0,0.0,2.0,1.0,3.0,0
39.0,0.0,3.0,138.0,220.0,0.0,0.0,152.0,0.0,0.0,2.0,0.0,3.0,0
57.0,1.0,2.0,154.0,232.0,0.0,2.0,164.0,0.0,0.0,1.0,1.0,3.0,1
58.0,0.0,4.0,130.0,197.0,0.0,0.0,131.0,0.0,0.6,2.0,0.0,3.0,0
57.0,1.0,4.0,110.0,335.0,0.0,0.0,143.0,1.0,3.0,2.0,1.0,7.0,2
47.0,1.0,3.0,130.0,253.0,0.0,0.0,179.0,0.0,0.0,1.0,0.0,3.0,0
55.0,0.0,4.0,128.0,205.0,0.0,1.0,130.0,1.0,2.0,2.0,1.0,7.0,3
35.0,1.0,2.0,122.0,192.0,0.0,0.0,174.0,0.0,0.0,1.0,0.0,3.0,0
61.0,1.0,4.0,148.0,203.0,0.0,0.0,161.0,0.0,0.0,1.0,1.0,7.0,2
58.0,1.0,4.0,114.0,318.0,0.0,1.0,140.0,0.0,4.4,3.0,3.0,6.0,4
58.0,0.0,4.0,170.0,225.0,1.0,2.0,146.0,1.0,2.8,2.0,2.0,6.0,2
58.0,1.0,2.0,125.0,220.0,0.0,0.0,144.0,0.0,0.4,2.0,?,7.0,0
56.0,1.0,2.0,130.0,221.0,0.0,2.0,163.0,0.0,0.0,1.0,0.0,7.0,0
56.0,1.0,2.0,120.0,240.0,0.0,0.0,169.0,0.0,0.0,3.0,0.0,3.0,0
67.0,1.0,3.0,152.0,212.0,0.0,2.0,150.0,0.0,0.8,2.0,0.0,7.0,1
55.0,0.0,2.0,132.0,342.0,0.0,0.0,166.0,0.0,1.2,1.0,0.0,3.0,0
44.0,1.0,4.0,120.0,169.0,0.0,0.0,144.0,1.0,2.8,3.0,0.0,6.0,2
63.0,1.0,4.0,140.0,187.0,0.0,2.0,144.0,1.0,4.0,1.0,2.0,7.0,2
63.0,0.0,4.0,124.0,197.0,0.0,0.0,136.0,1.0,0.0,2.0,0.0,3.0,1
41.0,1.0,2.0,120.0,157.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,3.0,0
59.0,1.0,4.0,164.0,176.0,1.0,2.0,90.0,0.0,1.0,2.0,2.0,6.0,3
57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [9]:
rows ,affect_row = [], []
for line in text.splitlines():
    srow = [data.strip() for data in line.split(',')]
    if len(srow)==14:
        rows.append(srow)
    else: 
        affect_row.append(srow)
print("Adding Rows completed")

Adding Rows completed

In [10]:
len(rows)

303

In [11]:
len(affect_row)

0

In [12]:
df = pd.DataFrame(data = rows, columns = cols)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [13]:
(df=='?').sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
num         0
dtype: int64

In [14]:
filepath = r"C:\Users\balaj\OneDrive\Desktop\disease prediction models\raw_data\reprocessed.hungarian.data".replace("\\", "/")
print(f"Modified File Path: {filepath}")

Modified File Path: C:/Users/balaj/OneDrive/Desktop/disease prediction models/raw_data/reprocessed.hungarian.data

In [15]:
with open(filepath, 'r') as f:
    text = f.read()

In [16]:
for line in text.splitlines():
    print(line)

40 1 2 140 289 0 0 172 0 0 -9 -9 -9 0
49 0 3 160 180 0 0 156 0 1 2 -9 -9 1
37 1 2 130 283 0 1 98 0 0 -9 -9 -9 0
48 0 4 138 214 0 0 108 1 1.5 2 -9 -9 3
54 1 3 150 -9 0 0 122 0 0 -9 -9 -9 0
39 1 3 120 339 0 0 170 0 0 -9 -9 -9 0
45 0 2 130 237 0 0 170 0 0 -9 -9 -9 0
54 1 2 110 208 0 0 142 0 0 -9 -9 -9 0
37 1 4 140 207 0 0 130 1 1.5 2 -9 -9 1
48 0 2 120 284 0 0 120 0 0 -9 -9 -9 0
37 0 3 130 211 0 0 142 0 0 -9 -9 -9 0
58 1 2 136 164 0 1 99 1 2 2 -9 -9 3
39 1 2 120 204 0 0 145 0 0 -9 -9 -9 0
49 1 4 140 234 0 0 140 1 1 2 -9 -9 3
42 0 3 115 211 0 1 137 0 0 -9 -9 -9 0
54 0 2 120 273 0 0 150 0 1.5 2 -9 -9 0
38 1 4 110 196 0 0 166 0 0 -9 -9 -9 1
43 0 2 120 201 0 0 165 0 0 -9 -9 -9 0
60 1 4 100 248 0 0 125 0 1 2 -9 -9 1
36 1 2 120 267 0 0 160 0 3 2 -9 -9 1
43 0 1 100 223 0 0 142 0 0 -9 -9 -9 0
44 1 2 120 184 0 0 142 0 1 2 -9 -9 0
49 0 2 124 201 0 0 164 0 0 -9 -9 -9 0
44 1 2 150 288 0 0 150 1 3 2 -9 -9 3
40 1 3 130 215 0 0 138 0 0 -9 -9 -9 0
36 1 3 130 209 0 0 178 0 0 -9 -9 -9 0
53 1 4 124 260 0 1 112 1 3 2 -9 -9 0
52 1 2 120 284 0 0 118 0 0 -9 -9 -9 0
53 0 2 113 468 -9 0 127 0 0 -9 -9 -9 0
51 1 2 125 188 0 0 145 0 0 -9 -9 -9 0
53 1 3 145 518 0 0 130 0 0 -9 -9 -9 3
56 1 3 130 -9 0 0 114 0 0 -9 -9 -9 0
54 1 4 125 224 0 0 122 0 2 2 -9 -9 1
41 1 4 130 172 0 1 130 0 2 2 -9 -9 3
43 0 2 150 186 0 0 154 0 0 -9 -9 -9 0
32 1 2 125 254 0 0 155 0 0 -9 -9 -9 0
65 1 4 140 306 1 0 87 1 1.5 2 -9 -9 1
41 0 2 110 250 0 1 142 0 0 -9 -9 -9 0
48 0 2 120 -9 1 1 148 0 0 -9 -9 -9 0
48 0 4 150 227 0 0 130 1 1 2 9 -9 0
54 0 2 150 230 0 0 130 0 0 -9 -9 -9 0
54 0 3 130 294 0 1 100 1 0 2 -9 -9 4
35 1 2 150 264 0 0 168 0 0 -9 -9 -9 0
52 1 3 140 259 0 1 170 0 0 -9 -9 -9 0
43 1 4 120 175 0 0 120 1 1 2 -9 7 3
59 1 3 130 318 0 0 120 1 1 2 -9 3 0
37 1 4 120 223 0 0 168 0 0 -9 -9 3 0
50 1 2 140 216 0 0 170 0 0 -9 -9 3 0
36 1 3 112 340 0 0 184 0 1 2 -9 3 0
41 1 4 110 289 0 0 170 0 0 -9 -9 6 1
50 1 4 130 233 0 0 121 1 2 2 -9 7 2
47 0 4 120 205 0 0 98 1 2 2 -9 6 4
45 1 2 140 224 1 0 122 0 0 -9 -9 -9 0
41 0 2 130 245 0 0 150 0 0 -9 -9 -9 0
52 0 4 130 180 0 0 140 1 1.5 2 -9 -9 0
51 0 2 160 194 0 0 170 0 0 -9 -9 -9 0
31 1 4 120 270 0 0 153 1 1.5 2 -9 -9 1
58 1 3 130 213 0 1 140 0 0 -9 -9 6 1
54 1 4 150 365 0 1 134 0 1 1 -9 -9 0
52 1 4 112 342 0 1 96 1 1 2 -9 -9 3
49 1 2 100 253 0 0 174 0 0 -9 -9 -9 0
43 0 3 150 -9 0 0 175 0 0 -9 -9 3 0
45 1 4 140 224 0 0 144 0 0 -9 -9 -9 0
46 1 4 120 277 0 0 125 1 1 2 -9 -9 1
50 0 2 110 202 0 0 145 0 0 -9 -9 -9 0
37 0 2 120 260 0 0 130 0 0 -9 -9 -9 0
45 0 4 132 297 0 0 144 0 0 -9 -9 -9 0
32 1 2 110 225 0 0 184 0 0 -9 -9 -9 0
52 1 4 160 246 0 1 82 1 4 2 -9 -9 3
44 1 4 150 412 0 0 170 0 0 -9 -9 -9 0
57 1 2 140 265 0 1 145 1 1 2 -9 -9 1
44 1 2 130 215 0 0 135 0 0 -9 -9 -9 0
52 1 4 120 182 0 0 150 0 0 -9 -9 -9 2
44 0 4 120 218 0 1 115 0 0 -9 -9 -9 0
55 1 4 140 268 0 0 128 1 1.5 2 -9 -9 2
46 1 3 150 163 -9 0 116 0 0 -9 -9 -9 0
32 1 4 118 529 0 0 130 0 0 -9 -9 -9 2
35 0 4 140 167 0 0 150 0 0 -9 -9 -9 0
52 1 2 140 100 0 0 138 1 0 -9 -9 -9 0
49 1 4 130 206 0 0 170 0 0 -9 -9 -9 1
55 1 3 110 277 0 0 160 0 0 -9 -9 -9 0
54 1 2 120 238 0 0 154 0 0 -9 -9 -9 0
63 1 4 150 223 0 0 115 0 0 -9 -9 -9 1
52 1 2 160 196 0 0 165 0 0 -9 -9 -9 0
56 1 4 150 213 1 0 125 1 1 2 -9 -9 2
66 1 4 140 -9 0 0 94 1 1 2 -9 -9 3
65 1 4 170 263 1 0 112 1 2 2 -9 -9 3
53 0 2 140 216 0 0 142 1 2 2 -9 -9 0
43 1 1 120 291 0 1 155 0 0 -9 -9 -9 2
55 1 4 140 229 0 0 110 1 0.5 2 -9 -9 0
49 0 2 110 -9 0 0 160 0 0 -9 -9 -9 0
39 1 4 130 307 0 0 140 0 0 -9 -9 -9 0
52 0 2 120 210 0 0 148 0 0 -9 -9 -9 0
48 1 4 160 329 0 0 92 1 1.5 2 -9 -9 2
39 0 3 110 182 0 1 180 0 0 -9 -9 -9 0
58 1 4 130 263 0 0 140 1 2 2 -9 -9 2
43 1 2 142 207 0 0 138 0 0 -9 -9 -9 0
39 1 3 160 147 1 0 160 0 0 -9 -9 -9 0
56 1 4 120 85 0 0 140 0 0 -9 -9 -9 0
41 1 2 125 269 0 0 144 0 0 -9 -9 -9 0
65 1 4 130 275 0 1 115 1 1 2 -9 -9 4
51 1 4 130 179 0 0 100 0 0 -9 -9 7 0
40 0 4 150 392 0 0 130 0 2 2 -9 6 2
40 1 4 120 466 -9 0 152 1 1 2 -9 6 1
46 1 4 118 186 0 0 124 0 0 -9 -9 7 1
57 1 2 140 260 1 0 140 0 0 -9 -9 6 0
48 0 4 120 254 0 1 110 0 0 -9 -9 -9 0
34 1 2 150 214 0 1 168 0 0 -9 -9 -9 0
50 1 4 140 129 0 0 135 0 0 -9 -9 -9 0
39 1 2 190 241 0 0 106 0 0 -9 -9 -9 0
59 0 2 130 188 0 0 124 0 1 2 -9 -9 0
57 1 4 150 255 0 0 92 1 3 2 -9 -9 2
47 1 4 140 276 1 0 125 1 0 -9 -9 -9 0
38 1 2 140 297 0 0 150 0 0 -9 -9 -9 0
49 0 3 130 207 0 1 135 0 0 -9 -9 -9 0
33 0 4 100 246 0 0 150 1 1 2 -9 -9 1
38 1 4 120 282 0 0 170 0 0 -9 -9 -9 1
59 0 4 130 338 1 1 130 1 1.5 2 -9 -9 1
35 0 1 120 160 0 1 185 0 0 -9 -9 -9 0
34 1 1 140 156 0 0 180 0 0 -9 -9 -9 1
47 0 3 135 248 1 0 170 0 0 -9 -9 -9 3
52 0 3 125 272 0 0 139 0 0 -9 -9 -9 0
46 1 4 110 240 0 1 140 0 0 -9 -9 3 0
58 0 2 180 393 0 0 110 1 1 2 -9 7 4
58 1 2 130 230 0 0 150 0 0 -9 -9 -9 0
54 1 2 120 246 0 0 110 0 0 -9 -9 -9 0
34 0 2 130 161 0 0 190 0 0 -9 -9 -9 0
48 0 4 108 163 0 0 175 0 2 1 -9 -9 0
54 0 2 120 230 1 0 140 0 0 -9 -9 -9 0
42 1 3 120 228 0 0 152 1 1.5 2 -9 -9 0
38 1 3 145 292 0 0 130 0 0 -9 -9 -9 0
46 1 4 110 202 0 0 150 1 0 -9 -9 -9 1
56 1 4 170 388 0 1 122 1 2 2 -9 -9 3
56 1 4 150 230 0 1 124 1 1.5 2 -9 -9 3
61 0 4 130 294 0 1 120 1 1 2 -9 -9 0
49 1 3 115 265 0 0 175 0 0 -9 -9 -9 1
43 0 2 120 215 0 1 175 0 0 -9 -9 -9 0
39 1 2 120 -9 0 1 146 0 2 1 -9 -9 0
54 1 4 140 -9 0 0 118 1 0 -9 -9 -9 2
43 1 4 150 247 0 0 130 1 2 2 -9 -9 1
52 1 4 160 331 0 0 94 1 2.5 -9 -9 -9 4
50 1 4 140 341 0 1 125 1 2.5 2 -9 -9 4
47 1 4 160 291 0 1 158 1 3 2 -9 -9 4
53 1 4 140 243 0 0 155 0 0 -9 -9 -9 0
56 0 2 120 279 0 0 150 0 1 2 -9 -9 3
39 1 4 110 273 0 0 132 0 0 -9 -9 -9 0
42 1 2 120 198 0 0 155 0 0 -9 -9 -9 0
43 0 2 120 249 0 1 176 0 0 -9 -9 -9 0
50 1 2 120 168 0 0 160 0 0 -9 0 -9 0
54 1 4 130 603 1 0 125 1 1 2 -9 -9 2
39 1 2 130 -9 0 0 120 0 0 -9 -9 -9 0
48 1 2 100 -9 0 0 100 0 0 -9 -9 -9 0
40 1 2 130 275 0 0 150 0 0 -9 -9 -9 0
55 1 4 120 270 0 0 140 0 0 -9 -9 -9 0
41 1 2 120 291 0 1 160 0 0 -9 -9 -9 0
56 1 4 155 342 1 0 150 1 3 2 -9 -9 4
38 1 4 110 -9 0 0 150 1 1 2 -9 -9 2
49 1 4 140 -9 0 0 130 0 0 -9 -9 -9 0
44 1 4 130 290 0 0 100 1 2 2 -9 -9 3
54 1 2 160 195 0 1 130 0 1 1 -9 -9 0
59 1 4 140 264 1 2 119 1 0 -9 -9 -9 3
49 1 4 128 212 0 0 96 1 0 -9 -9 -9 4
47 1 2 160 263 0 0 174 0 0 -9 -9 -9 0
49 0 2 110 -9 0 0 160 0 0 -9 -9 -9 0
42 1 2 120 196 0 0 150 0 0 -9 -9 -9 0
52 0 2 140 -9 0 0 140 0 0 -9 -9 -9 0
46 1 1 140 272 1 0 175 0 2 2 -9 -9 3
50 1 4 140 231 0 1 140 1 5 2 -9 -9 4
48 1 2 140 238 0 0 118 0 0 -9 -9 -9 0
58 1 4 135 222 0 0 100 0 0 -9 -9 -9 0
58 1 3 140 179 0 0 160 0 0 -9 -9 -9 0
29 1 2 120 243 0 0 160 0 0 -9 -9 -9 0
40 1 3 140 -9 0 0 188 0 0 -9 -9 -9 0
53 1 2 140 320 0 0 162 0 0 -9 -9 -9 0
49 1 3 140 187 0 0 172 0 0 -9 -9 -9 0
52 1 4 140 266 0 0 134 1 2 2 -9 -9 4
43 1 4 140 288 0 0 135 1 2 2 -9 -9 4
54 1 4 140 216 0 0 105 0 1.5 2 -9 -9 3
59 1 2 140 287 0 0 150 0 0 -9 -9 -9 0
37 1 3 130 194 0 0 150 0 0 -9 -9 -9 0
46 0 4 130 238 0 0 90 0 0 -9 -9 -9 0
52 1 4 130 225 0 0 120 1 2 2 -9 -9 1
51 1 2 130 224 0 0 150 0 0 -9 -9 -9 0
52 1 4 140 404 0 0 124 1 2 2 -9 -9 3
46 1 4 110 238 0 1 140 1 1 2 -9 3 0
54 0 2 160 312 0 0 130 0 0 -9 -9 -9 0
58 1 3 160 211 1 1 92 0 0 -9 -9 -9 2
58 1 2 130 251 0 0 110 0 0 -9 -9 -9 0
41 1 4 120 237 -9 0 138 1 1 2 -9 -9 1
50 0 4 120 328 0 0 110 1 1 2 -9 -9 0
53 1 4 180 285 0 1 120 1 1.5 2 -9 -9 3
46 1 4 180 280 0 1 120 0 0 -9 -9 -9 0
50 1 2 170 209 0 1 116 0 0 -9 -9 -9 0
48 1 2 130 245 0 0 160 0 0 -9 -9 -9 0
45 1 3 135 -9 0 0 110 0 0 -9 -9 -9 0
41 0 2 125 184 0 0 180 0 0 -9 -9 -9 0
62 0 1 160 193 0 0 116 0 0 -9 -9 -9 0
49 1 4 120 297 -9 0 132 0 1 2 -9 -9 0
42 1 2 150 268 0 0 136 0 0 -9 -9 -9 0
53 1 4 120 246 0 0 116 1 0 -9 -9 -9 2
57 0 1 130 308 0 0 98 0 1 2 -9 -9 0
47 1 1 110 249 0 0 150 0 0 -9 -9 -9 0
46 1 3 120 230 0 0 150 0 0 -9 -9 -9 0
42 1 3 160 147 0 0 146 0 0 -9 -9 -9 0
31 0 2 100 219 0 1 150 0 0 -9 -9 -9 0
56 1 2 130 184 0 0 100 0 0 -9 -9 -9 0
50 1 4 150 215 0 0 140 1 0 -9 -9 -9 0
35 1 2 120 308 0 2 180 0 0 -9 -9 -9 0
35 1 2 110 257 0 0 140 0 0 -9 -9 -9 1
28 1 2 130 132 0 2 185 0 0 -9 -9 -9 0
54 1 4 125 216 0 0 140 0 0 -9 -9 -9 1
48 1 4 106 263 1 0 110 0 0 -9 -9 -9 1
50 0 3 140 288 0 0 140 1 0 -9 -9 7 1
56 1 3 130 276 0 0 128 1 1 1 -9 6 0
56 0 3 130 219 -9 1 164 0 0 -9 -9 7 0
47 1 4 150 226 0 0 98 1 1.5 2 0 7 1
30 0 1 170 237 0 1 170 0 0 -9 -9 6 0
39 1 4 110 280 0 0 150 0 0 -9 -9 6 2
54 1 3 120 217 0 0 137 0 0 -9 -9 -9 0
55 1 2 140 196 0 0 150 0 0 -9 -9 7 0
29 1 2 140 -9 0 0 170 0 0 -9 -9 -9 0
46 1 4 130 222 0 0 112 0 0 -9 -9 -9 2
51 0 4 160 303 0 0 150 1 1 2 -9 -9 1
48 0 3 120 195 0 0 125 0 0 -9 -9 -9 0
33 1 3 120 298 0 0 185 0 0 -9 -9 -9 0
55 1 2 120 256 1 0 137 0 0 -9 -9 7 0
50 1 4 145 264 0 0 150 0 0 -9 -9 -9 1
53 1 3 120 195 0 0 140 0 0 -9 -9 -9 0
38 1 4 92 117 0 0 134 1 2.5 2 -9 -9 1
41 1 2 120 295 0 0 170 0 0 -9 -9 -9 0
37 0 4 130 173 0 1 184 0 0 -9 -9 -9 0
37 1 4 130 315 0 0 158 0 0 -9 -9 -9 0
40 1 3 130 281 0 0 167 0 0 -9 -9 -9 0
38 0 2 120 275 -9 0 129 0 0 -9 -9 -9 0
41 1 4 112 250 0 0 142 0 0 -9 -9 -9 0
54 0 2 140 309 -9 1 140 0 0 -9 -9 -9 0
39 1 2 120 200 0 0 160 1 1 2 -9 -9 0
41 1 4 120 336 0 0 118 1 3 2 -9 -9 4
55 1 1 140 295 0 -9 136 0 0 -9 -9 -9 3
48 1 4 160 355 0 0 99 1 2 2 -9 -9 2
48 1 4 160 193 0 0 102 1 3 2 -9 -9 2
55 1 2 145 326 0 0 155 0 0 -9 -9 -9 0
54 1 4 200 198 0 0 142 1 2 2 -9 -9 2
55 1 2 160 292 1 0 143 1 2 2 -9 -9 3
43 0 2 120 266 0 0 118 0 0 -9 -9 -9 0
48 1 4 160 268 0 0 103 1 1 2 -9 -9 1
54 1 1 120 171 0 0 137 0 2 1 -9 -9 0
54 1 3 120 237 0 0 150 1 1.5 -9 -9 7 2
48 1 4 122 275 1 1 150 1 2 3 -9 -9 2
45 1 4 130 219 0 1 130 1 1 2 -9 -9 2
49 1 4 130 341 0 0 120 1 1 2 -9 -9 3
44 1 4 135 491 0 0 135 0 0 -9 -9 -9 4
48 1 4 120 260 0 0 115 0 2 2 -9 -9 1
61 1 4 125 292 0 1 115 1 0 -9 -9 -9 0
62 1 2 140 271 0 0 152 0 1 1 -9 -9 0
55 1 4 145 248 0 0 96 1 2 2 -9 -9 3
53 0 3 120 274 0 0 130 0 0 -9 -9 -9 0
55 0 2 130 394 0 2 150 0 0 -9 -9 -9 0
36 1 3 150 160 0 0 172 0 0 -9 -9 -9 0
51 0 3 150 200 0 0 120 0 0.5 1 -9 -9 0
55 0 2 122 320 0 0 155 0 0 -9 -9 -9 0
46 1 2 140 275 0 0 165 1 0 -9 -9 -9 0
54 0 2 120 221 0 0 138 0 1 1 -9 -9 0
46 1 4 120 231 0 0 115 1 0 -9 -9 -9 2
59 1 4 130 -9 0 0 125 0 0 -9 -9 -9 3
47 1 3 140 193 0 0 145 1 1 2 -9 -9 1
54 1 2 160 305 0 0 175 0 0 -9 -9 -9 0
52 1 4 130 298 0 0 110 1 1 2 -9 -9 3
34 1 2 98 220 0 0 150 0 0 -9 -9 -9 0
54 1 4 130 242 0 0 91 1 1 2 -9 -9 2
47 0 3 130 -9 0 0 145 0 2 2 -9 -9 0
45 1 4 120 225 0 0 140 0 0 -9 -9 -9 0
32 0 2 105 198 0 0 165 0 0 -9 -9 -9 0
55 1 4 140 201 0 0 130 1 3 2 -9 -9 1
55 1 3 120 220 0 2 134 0 0 -9 -9 -9 0
45 0 2 180 -9 0 0 180 0 0 -9 -9 -9 0
59 1 3 180 213 0 0 100 0 0 -9 -9 -9 0
51 1 3 135 160 0 0 150 0 2 2 -9 -9 3
52 1 4 170 -9 0 0 126 1 1.5 2 -9 -9 2
57 0 4 180 347 0 1 126 1 0.8 2 -9 -9 0
54 0 2 130 253 0 1 155 0 0 -9 -9 -9 0
60 1 3 120 246 0 2 135 0 0 -9 -9 -9 0
49 1 4 150 222 0 0 122 0 2 2 -9 -9 4
51 0 3 130 220 0 0 160 1 2 1 -9 -9 0
55 0 2 110 344 0 1 160 0 0 -9 -9 -9 0
42 1 4 140 358 0 0 170 0 0 -9 -9 -9 0
51 0 3 110 190 0 0 120 0 0 -9 -9 -9 0
59 1 4 140 -9 0 0 140 0 0 -9 0 -9 0
53 1 2 120 -9 0 0 132 0 0 -9 -9 -9 0
48 0 2 -9 308 0 1 -9 -9 2 1 -9 -9 0
36 1 2 120 166 0 0 180 0 0 -9 -9 -9 0
48 1 3 110 211 0 0 138 0 0 -9 -9 6 0
47 0 2 140 257 0 0 135 0 1 1 -9 -9 0
53 1 4 130 182 0 0 148 0 0 -9 -9 -9 0

In [17]:
rows ,affect_row = [], []
for line in text.splitlines():
    srow = [data.strip() for data in line.split(' ')]
    if len(srow)==14:
        rows.append(srow)
    else: 
        affect_row.append(srow)
print("Adding Rows completed")

Adding Rows completed

In [18]:
df1 = pd.DataFrame(data = rows, columns = cols)
df1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40,1,2,140,289,0,0,172,0,0,-9,-9,-9,0
1,49,0,3,160,180,0,0,156,0,1,2,-9,-9,1
2,37,1,2,130,283,0,1,98,0,0,-9,-9,-9,0
3,48,0,4,138,214,0,0,108,1,1.5,2,-9,-9,3
4,54,1,3,150,-9,0,0,122,0,0,-9,-9,-9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,36,1,2,120,166,0,0,180,0,0,-9,-9,-9,0
291,48,1,3,110,211,0,0,138,0,0,-9,-9,6,0
292,47,0,2,140,257,0,0,135,0,1,1,-9,-9,0
293,53,1,4,130,182,0,0,148,0,0,-9,-9,-9,0
294,,,,,,,,,,,,,,

# Another Dataset

In [19]:
fp = r"C:\Users\balaj\OneDrive\Desktop\disease prediction models\raw_data\heart.csv".replace('\\','/')
hd = pd.read_csv(fp)

In [20]:
hd.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [21]:
hd.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [24]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [25]:
obj = hd.select_dtypes(include="object")
enc = ce.OrdinalEncoder(obj)
hde = pd.DataFrame(data = enc.fit_transform(hd), columns=hd.columns)
hde

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,1,0.0,1,0
1,49,2,2,160,180,0,1,156,1,1.0,2,1
2,37,1,1,130,283,0,2,98,1,0.0,1,0
3,48,2,3,138,214,0,1,108,2,1.5,2,1
4,54,1,2,150,195,0,1,122,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,4,110,264,0,1,132,1,1.2,2,1
914,68,1,3,144,193,1,1,141,1,3.4,2,1
915,57,1,3,130,131,0,1,115,2,1.2,2,1
916,57,2,1,130,236,0,3,174,1,0.0,2,1
917,38,1,2,138,175,0,1,173,1,0.0,1,0

In [27]:
hde.to_csv('C:/Users/balaj/OneDrive/Desktop/disease prediction models/good dataset/heart_disease.csv', index=False)